





/**
 * AUTH
 */
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER'

/**
 * NOTIFICATIONS
 */
export const NOTIFICATIONS_SEND = 'NOTIFICATIONS_SEND'
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR'




